#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '...testing & building...'

npm run lint ||
(
        echo '❌ ts & eslint failed'
        false; 
)

echo '...building...'

npm run build ||
(
    echo '❌ build failed'
    false;
)

echo '✅ committing successfully'